---
title: "02_lake_merge_QA"
author: "Simon Topp"
date: "7/26/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(googledrive)
library(scales)
```

## Download Lake Area Tables

```{r cars}

#Landsat
path <- 'UNC_LakeAreasLS'
desitnation <- 'areas/ls/'
files <- drive_ls(path)

for (i in 1:length(files$name)){
        name = files$name[i]
        drive_download(paste0(path,'/',name), paste0(desitnation,name),
                       overwrite = T)
}

#Sentinel2
path <- 'UNC_LakeAreasS2'
desitnation <- 'areas/s2/'
files <- drive_ls(path)

for (i in 1:length(files$name)){
        name = files$name[i]
        drive_download(paste0(path,'/',name), paste0(desitnation,name),
                       overwrite = T)
}

```


## Download scripts for various checks (i.e. 10 meter resolution Sentinel 2, different ndwi thresholds)

```{r}


#Sentinel2.double cloud filt (much better)
path <- 'UNC_LakeAreasS2_clouds2'
desitnation <- 'areas/s2_clouds2/'
files <- drive_ls(path)

for (i in 1:length(files$name)){
        name = files$name[i]
        drive_download(paste0(path,'/',name), paste0(desitnation,name),
                       overwrite = T)
}

#Sentinel 2 10meter res

path <- 'UNC_LakeAreasS2_10m'
desitnation <- 'areas/s2_10m/'
files <- drive_ls(path)

for (i in 1:length(files$name)){
        name = files$name[i]
        drive_download(paste0(path,'/',name), paste0(desitnation,name),
                       overwrite = T)
}

#Sentinel 2 30 meter 0.1 threshold

path <- 'UNC_LakeAreasS2_cThresh'
desitnation <- 'areas/s2_cThresh/'
files <- drive_ls(path)

for (i in 1:length(files$name)){
        name = files$name[i]
        drive_download(paste0(path,'/',name), paste0(desitnation,name),
                       overwrite = T)
}

#Landsat 0.1 threshold

path <- 'UNC_LakeAreasLS_cThresh'
desitnation <- 'areas/LS_cThresh/'
files <- drive_ls(path)

for (i in 1:length(files$name)){
        name = files$name[i]
        drive_download(paste0(path,'/',name), paste0(desitnation,name),
                       overwrite = T)
}


s2.2 <- list.files('areas/s2_clouds2', full.names = T) %>%
        map(read_csv) %>%
        reduce(rbind) %>%
  mutate(sat = 's2.2')

s2.10m <- list.files('areas/s2_10m', full.names = T) %>%
        map(read_csv) %>%
        reduce(rbind) %>%
  mutate(sat = 's2.10m')

s2.ct <- list.files('areas/s2_cThresh', full.names = T) %>%
        map(read_csv) %>%
        reduce(rbind) %>%
  mutate(sat = 's2.ct')

ls.ct <- list.files('areas/ls_cThresh', full.names = T) %>%
        map(read_csv) %>%
        reduce(rbind) %>%
  mutate(sat = 'ls.ct')

```


## Merge Files and Compare to Old Data

```{r pressure, echo=FALSE}

#Bring in old Data to Compare
old <- read.csv('areas/NCSC_Full_Old.csv')  %>%
    mutate(Date = as.Date(Date),
           Mission = as.character(Mission)) %>%
           rename(sat = Mission)
old$sat[old$sat =='L8RT'] = 'LS'

#Read in new files and merge into one dataframe
ls <- list.files('areas/ls', full.names = T) %>%
        map(read_csv) %>%
        reduce(rbind) %>%
  mutate(sat = 'LS',
         tile = 'none')

s2 <- list.files('areas/s2', full.names = T) %>%
        map(read_csv) %>%
        reduce(rbind) %>%
  mutate(sat = 'S2',
         tile = path,
         path = 999,
         row = 999)


areas <- ls %>%
  bind_rows(s2)%>%
    select(-.geo) %>%
  mutate(Date = as.Date(Date),
         AreaKm = round(Area/1000000, digits = 4),
         ID = paste0(sat,'_',GNIS_NAME,'_',Date)) %>%
  rename(lakeName = GNIS_NAME, NHD_Area = AREASQKM)

#write.csv(areas, 'areas/full.preQA.20180803.csv')


## Filter to dates of interest for publication and filter out images flagged from visual qa

## Remove values from visual qa check
vis.qa <- read.csv('qaRemoveList.csv') %>%
  mutate(ID = paste0(sat,'_',lakeName,'_',Date)) %>%
  filter(Reason != 'sheen') #Not sure if sheen is actual qa issue.  The area masks look fine but are 
                            #generally larger than average, which would make sense if sheen is really 
                            #just turbid water from large rain event.

area.qa <- areas %>% 
  filter(Date > '2017-03-22') %>%
  filter(!(ID %in% vis.qa$ID))


##Remove partial tiles
area.qa <- area.qa %>%
  filter(!(lakeName == 'Lake Waccamaw' & tile == '17SQT'),
         !(lakeName == 'Catfish Lake' & tile == '18STD'))


## Visualize
ggplot(area.qa, aes(x = AreaKm, color = sat)) + geom_histogram(bins = 8) + facet_wrap(~lakeName, scales = 'free')

ggplot(area.qa, aes(x = Date, y = AreaKm, color = sat)) + 
        geom_line() + 
        facet_grid(lakeName ~., scales = 'free') +
  scale_x_date(breaks = pretty_breaks(n = 20)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#ggsave('figures/timeSeriesNew.png', height = 9, width = 6.5, units = 'in')

##Check against old data
comp <- area.qa %>%
  filter(Date < '2018-02-01')

ggplot(comp, aes(x = Date, y = AreaKm)) + 
  geom_line(aes(color = 'New')) +
  geom_line(data = old, aes(color = 'Old')) +
  geom_point(aes(shape = sat)) +
  facet_grid(lakeName ~., scales = 'free') +
  scale_x_date(breaks = pretty_breaks(n = 20)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

check <- area.qa %>%
  filter(!(Date == '2018-04-19' & lakeName == 'Singletary Lake' & sat == 'S2'))

#ggsave('figures/timeSeriesComp.png', height = 9, width = 6.5, units = 'in')

comp.sum <- area.qa %>%
  filter(Date < '2018-02-01') %>%
  group_by(sat, lakeName) %>%
  summarise(New = n()) %>%
  left_join(old %>% 
              group_by(sat, lakeName) %>% summarize(Old = n())) %>%
  gather(New:Old, key = 'Series', value = 'Count')

ggplot(comp, aes(x = lakeName, y = Count, fill = Series)) + geom_col(position = 'dodge') +
  facet_wrap(~sat, nrow = 2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#ggsave('figures/countComparison.png')

## Write post qa csv.

write.csv(area.qa, 'areas/full.postQA.20180803.csv')

```


## Break-up data into indivudal 

```{r}
names <- unique(area.qa$lakeName)

for (i in 1:length(names)){
  out <- area.qa %>% filter(lakeName == names[i]) %>%
  select(Lake = lakeName, Date, Sat = sat, Area = AreaKm, Scene = 'system:index')
  write.csv(out, paste0('areas/byLake/', names[i], '.csv'))
}

```

